version: '3.8'

services:
  api_gateway:
    image: api_gateway_image
    build:
      context: ./api_gateway
      dockerfile: Dockerfile
    ports:
      - "8020:8020"
    depends_on:
      - login
      - rutas

  login:
    image: login_image
    build:
      context: ./login
      dockerfile: Dockerfile
    ports:
      - "5020:5020"

  rutas:
    image: rutas_image
    build:
      context: ./gestion_rutas
      dockerfile: Dockerfile
    ports:
      - "4043:4043"
