version: '3.8'

services:
  api_gateway:
    image: api_gateway_image
    build:
      context: ./api_gateway
      dockerfile: Dockerfile
    ports:
      - "8020:8020"
    depends_on:
      - login
      - gestion_rutas

  login:
    image: gestion_pedidos_image
    build:
      context: ./gestion_pedidos
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - DATABASE_HOST=sqlite:///pedidos.db

  gestion_rutas:
    image: gestion_inventarios_image
    build:
      context: ./gestion_inventarios
      dockerfile: Dockerfile
    ports:
      - "4043:4043"
